### ISSUE TITLE
Закончить фильтры

### ISSUE THREAD

**Issue by DoctorCotic** [sonm-io/Fusrodah#2]
- [x] Задокументировать все новые функции (добавьте комментарии в коде) перед каждой новой добавленной функцией

- [x] В ридми добавить описание цикла работы системы с описанием работы новых функций.
Например:
"майнер при старте функции startDiscovery отправляет сообщение с топиками "hub"."discovery", и ожидает ответа от хаба, который посылает информацию о себе с топиками "hub","discovery","response".

- [x] Нужно либо сделать нормальный хотспот, уменьшив TTL до двух часов, либо сделать броадкаст хабов по "тику", т.е. допустим броадкастить сообщение каждые 6 часов, а не по запросу.

- [x] Тесты должны быть оформлены в отдельный файл, вроде test.go, куда подключается пакет fusrodah

- [x] Фильтры так же должны быть в обязательном порядке вынесены в отдельный пакет.

- [x] В хэндлинг мы должны обязательно добавлять операнд проверки структуры сообщения перед его использованием. т.е. проверять, что сообщение состоит из нужных нам полей, а не рандомного белого шума флудеров.

**Comment by JackBekket** [comment]
Отпишите мне в личку когда закончите плз

**Comment by Sokel** [comment]
Closed.
