### ISSUE TITLE
Why a hacked version?

### ISSUE THREAD

**Issue by obscuren** [sonm-io/fusrodah#3]
I just saw this repo and I couldn't find any reason why SONM uses a custom/hacked version of the Whisper protocol and Go Ethereum repo.

If there's anything missing from our repo or something that doesn't work we'd much rather hear about it and fix it, collaboration makes us stronger :-)

**Comment by Sokel** [comment]
Good day @obscuren !
Today we are back to go-ethereum repo.
But we think api to whisper protocol can be smart and lazy)
You may connect with me with my email.
Hope for strenght colloboration)
